#!/usr/bin/env bash
source .env

echo ""
echo "Setting up ${PROJECT_NAME}"
echo ""

echo "Pulling docker images"
echo "================================"
docker-compose pull

echo ""
echo "Installing frontend dependencies"
echo "================================"
docker run --rm -ti --env-file .env -v "$PWD"/frontend:/src -w /src node:$NODE_VERSION npm i

echo ""
echo "Installing admin dependencies"
echo "================================"
docker run --rm -ti --env-file .env -v "$PWD"/admin:/src -w /src node:$NODE_VERSION npm i

echo ""
echo "Installing api dependencies"
echo "================================"
docker run --rm -ti --env-file .env -v "$PWD"/api:/src -w /src node:$NODE_VERSION npm i

docker-compose up -d

docker run --rm -v "$PWD":/src -w /src --link "$(basename $PWD)"_postgres_1:postgres --net "$(basename $PWD)"_default --name pg_init_db_w8 appropriate/nc sh -c "echo \"Waiting for postgres container...\"; until nc -z postgres 5432 &> /dev/null; do sleep 2; done"

./migrate

echo ""
echo "    +-------------------------------------------------------------------+"
echo "    | It seems that the installation was successful.                    |"
echo "    | Now open http://localhost for main app                            |"
echo "    | and http://localhost:8520 for admin panel                         |"
echo "    | Login: admin@mail.ru                                              |"
echo "    | Password: admin                                                   |"
echo "    +-------------------------------------------------------------------+"
echo ""
