#!/usr/bin/env bash
if [ "$1" == "create" ]; then
  docker-compose exec api node_modules/.bin/sequelize --env=db --config=config.js --migrations-path=db/migrations migration:create --name="${@:2}"
elif [ "$1" == "down" ]; then
  docker-compose exec api node_modules/.bin/sequelize --env=db --config=config.js --migrations-path=db/migrations db:migrate:undo
else
  docker-compose exec api node_modules/.bin/sequelize --env=db --config=config.js --migrations-path=db/migrations db:migrate
fi